apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-application-deployment
  labels:
    app: express-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-application
  template:
    metadata:
      labels:
        app: express-application
    spec:
      containers:
        - name: express-application
          image: razzaksr/express-stand-kube:latest
          ports:
            - containerPort: 4433
          env:
            - name: mongo
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: mongo

---
apiVersion: v1
kind: Service
metadata:
  name: express-application-service
spec:
  type: NodePort
  selector:
    app: express-application
  ports:
    - protocol: TCP
      port: 4433
      targetPort: 4433
      NodePort: 32749
